# Generated by Django 3.0.2 on 2020-01-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0005_todoitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(
                choices=[(1, 'Высокий приоритет'), (2, 'Средний приоритет'), (3, 'Низкий приоритет')], default=2,
                verbose_name='Приоритет'),
        ),
    ]
