# Generated by Django 3.0.2 on 2020-01-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20200124_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars/%Y/%m/%d'),
        ),
    ]
